name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: build release
        run: |
          pip install poetry dunamai
          poetry version $(dunamai from git --dirty)
          poetry build --no-interaction

      - name: push release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.tar.gz,dist/*.whl"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update pypi
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches
          owner: uwcip
          repo: pypi
          workflow: generate-index.yaml
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - uses: 8398a7/action-slack@v3
        continue-on-error: true
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              "attachments": [{
                "color": "${{ job.status }}" === "success" ? "#198754" : "${{ job.status }}" === "failure" ? "#DC3545" : "#FFC107",
                "title": "${{ job.status }}" === "success" ? `:white_check_mark: SUCCESS - ${process.env.AS_JOB} completed on ${process.env.AS_REPO}` : "${{ job.status }}" === "failure" ? `:no_entry: FAILURE - ${process.env.AS_JOB} failed on ${process.env.AS_REPO}` : `:warning: CANCELED - ${process.env.AS_JOB} canceled on ${process.env.AS_REPO}`,
                "fields": [
                  {"title": "Job", "value": `${process.env.AS_JOB}`, "short": true},
                  {"title": "Workflow", "value": `${process.env.AS_WORKFLOW}`, "short": true},
                  {"title": "Branch", "value": `${process.env.AS_REF.split("/")[2]}`, "short": true},
                  {"title": "Commit", "value": `${process.env.AS_COMMIT}`, "short": true},
                  {"title": "Author", "value": `${process.env.AS_AUTHOR}`, "short": false},
                  {"title": "Message", "value": `${process.env.AS_MESSAGE}`, "short": false}
                ],
                "ts": `${Math.floor(Date.now() / 1000)}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
