name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: build release
        run: |
          pip install poetry dunamai
          poetry version $(dunamai from git --dirty)
          poetry build --no-interaction

      - name: push release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.tar.gz,dist/*.whl"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update pypi
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow}/dispatches
          owner: uwcip
          repo: pypi
          workflow: generate-index.yaml
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
